import unreal


# ============================================================
# CONFIGURABLE MECCHA ARENA BLOCKOUT GENERATOR
# Unreal Engine 5.6 / Meccha Chameleon UGC
# ============================================================
# Run while the destination map is open.
# Re-running removes only actors generated by this script.
# Adjust the configuration values below before running.
# ============================================================

ARENA_NAME = "MecchaArena"
ARENA_WIDTH = 5200.0
ARENA_LENGTH = 5200.0

FLOOR_TOP_Z = -905.0
FLOOR_THICKNESS = 50.0
WALL_TOP_Z = 0.0
WALL_THICKNESS = 150.0
WALL_OVERLAP_BELOW_FLOOR = 30.0

GRID_COLUMNS = 4
GRID_ROWS = 3
PANEL_WIDTH = 1250.0
PANEL_LENGTH = 1600.0
PANEL_THICKNESS = 6.2
PANEL_TOP_Z = -899.9
PANEL_GAP = 0.0
PANEL_EDGE_OVERLAP = 2.0
CREATE_GRID_PANELS = True

SPAWN_LOCATION = unreal.Vector(0.0, 0.0, 100.0)
CREATE_LIGHTING = True
DIRECTIONAL_LIGHT_INTENSITY = 5.0
SKY_LIGHT_INTENSITY = 1.0
DIRECTIONAL_LIGHT_ROTATION = unreal.Rotator(-55.0, -30.0, 0.0)

FLOOR_COLLISION_PROFILE = "BlockAll"
WALL_COLLISION_PROFILE = "CameraBlockWall"
ENGINE_CUBE_PATH = "/Engine/BasicShapes/Cube.Cube"

GENERATED_TAG = "MecchaConfigurableArenaGenerated"
ROOT_FOLDER = f"{ARENA_NAME}"
SHELL_FOLDER = f"{ROOT_FOLDER}/ArenaShell"
PANEL_FOLDER = f"{ROOT_FOLDER}/Panels"
SPAWN_FOLDER = f"{ROOT_FOLDER}/Spawn"
LIGHT_FOLDER = f"{ROOT_FOLDER}/Lighting"


def log(message):
    unreal.log(f"[Configurable Arena] {message}")


def get_subsystems():
    actor_subsystem = unreal.get_editor_subsystem(unreal.EditorActorSubsystem)
    level_subsystem = unreal.get_editor_subsystem(unreal.LevelEditorSubsystem)
    if not actor_subsystem or not level_subsystem:
        raise RuntimeError("Required Unreal Editor subsystems are unavailable.")
    return actor_subsystem, level_subsystem


def load_asset_checked(asset_path):
    asset = unreal.EditorAssetLibrary.load_asset(asset_path)
    if not asset:
        raise RuntimeError(f"Could not load required asset: {asset_path}")
    return asset


def actor_has_generated_tag(actor):
    try:
        return any(
            str(tag) == GENERATED_TAG
            for tag in actor.get_editor_property("tags")
        )
    except Exception:
        return False


def clear_previous_generated_actors(actor_subsystem):
    actors = [
        actor
        for actor in actor_subsystem.get_all_level_actors()
        if actor_has_generated_tag(actor)
    ]
    for actor in actors:
        actor_subsystem.destroy_actor(actor)
    log(f"Removed {len(actors)} previously generated actors.")


def configure_actor(actor, label, folder):
    actor.set_actor_label(label)
    actor.set_folder_path(unreal.Name(folder))
    actor.set_editor_property("tags", [unreal.Name(GENERATED_TAG)])


def create_cube(
    actor_subsystem,
    cube_mesh,
    label,
    location,
    dimensions,
    folder,
    collision_enabled,
    collision_profile=None,
    cast_shadow=True,
):
    actor = actor_subsystem.spawn_actor_from_class(
        unreal.StaticMeshActor,
        location,
        unreal.Rotator(),
        False,
    )
    if not actor:
        raise RuntimeError(f"Failed to spawn {label}")

    configure_actor(actor, label, folder)
    component = actor.static_mesh_component
    component.set_static_mesh(cube_mesh)
    component.set_editor_property("mobility", unreal.ComponentMobility.STATIC)
    component.set_editor_property("cast_shadow", cast_shadow)
    component.set_editor_property("generate_overlap_events", False)
    component.set_collision_enabled(collision_enabled)

    if collision_profile:
        component.set_collision_profile_name(unreal.Name(collision_profile))

    actor.set_actor_enable_collision(
        collision_enabled != unreal.CollisionEnabled.NO_COLLISION
    )
    actor.set_actor_scale3d(
        unreal.Vector(
            dimensions.x / 100.0,
            dimensions.y / 100.0,
            dimensions.z / 100.0,
        )
    )
    return actor


def centered_positions(count, item_size, gap):
    spacing = item_size + gap
    offset = (count - 1) / 2.0
    return [(index - offset) * spacing for index in range(count)]


def validate_configuration():
    if ARENA_WIDTH <= 0 or ARENA_LENGTH <= 0:
        raise RuntimeError("Arena dimensions must be greater than zero.")
    if FLOOR_THICKNESS <= 0 or WALL_THICKNESS <= 0:
        raise RuntimeError("Floor and wall thickness must be greater than zero.")
    if WALL_TOP_Z <= FLOOR_TOP_Z:
        raise RuntimeError("WALL_TOP_Z must be above FLOOR_TOP_Z.")
    if CREATE_GRID_PANELS:
        grid_width = GRID_COLUMNS * PANEL_WIDTH + (GRID_COLUMNS - 1) * PANEL_GAP
        grid_length = GRID_ROWS * PANEL_LENGTH + (GRID_ROWS - 1) * PANEL_GAP
        if grid_width > ARENA_WIDTH or grid_length > ARENA_LENGTH:
            raise RuntimeError("The configured panel grid does not fit inside the arena.")


def build_arena():
    actor_subsystem, level_subsystem = get_subsystems()
    if level_subsystem.is_in_play_in_editor():
        raise RuntimeError("Stop Play In Editor before generating the arena.")

    validate_configuration()
    cube_mesh = load_asset_checked(ENGINE_CUBE_PATH)
    clear_previous_generated_actors(actor_subsystem)
    created = []

    floor_center_z = FLOOR_TOP_Z - FLOOR_THICKNESS / 2.0
    created.append(
        create_cube(
            actor_subsystem,
            cube_mesh,
            f"SM_{ARENA_NAME}_Floor_TEMP",
            unreal.Vector(0.0, 0.0, floor_center_z),
            unreal.Vector(ARENA_WIDTH, ARENA_LENGTH, FLOOR_THICKNESS),
            SHELL_FOLDER,
            unreal.CollisionEnabled.QUERY_AND_PHYSICS,
            FLOOR_COLLISION_PROFILE,
        )
    )

    wall_bottom_z = FLOOR_TOP_Z - WALL_OVERLAP_BELOW_FLOOR
    wall_height = WALL_TOP_Z - wall_bottom_z
    wall_center_z = wall_bottom_z + wall_height / 2.0
    half_width = ARENA_WIDTH / 2.0
    half_length = ARENA_LENGTH / 2.0

    wall_specs = [
        (
            "North",
            unreal.Vector(0.0, half_length + WALL_THICKNESS / 2.0, wall_center_z),
            unreal.Vector(ARENA_WIDTH + WALL_THICKNESS * 2.0, WALL_THICKNESS, wall_height),
        ),
        (
            "South",
            unreal.Vector(0.0, -(half_length + WALL_THICKNESS / 2.0), wall_center_z),
            unreal.Vector(ARENA_WIDTH + WALL_THICKNESS * 2.0, WALL_THICKNESS, wall_height),
        ),
        (
            "East",
            unreal.Vector(half_width + WALL_THICKNESS / 2.0, 0.0, wall_center_z),
            unreal.Vector(WALL_THICKNESS, ARENA_LENGTH + WALL_THICKNESS * 2.0, wall_height),
        ),
        (
            "West",
            unreal.Vector(-(half_width + WALL_THICKNESS / 2.0), 0.0, wall_center_z),
            unreal.Vector(WALL_THICKNESS, ARENA_LENGTH + WALL_THICKNESS * 2.0, wall_height),
        ),
    ]

    for side, location, dimensions in wall_specs:
        created.append(
            create_cube(
                actor_subsystem,
                cube_mesh,
                f"SM_{ARENA_NAME}_Wall_{side}_TEMP",
                location,
                dimensions,
                SHELL_FOLDER,
                unreal.CollisionEnabled.QUERY_AND_PHYSICS,
                WALL_COLLISION_PROFILE,
            )
        )

    if CREATE_GRID_PANELS:
        x_positions = centered_positions(GRID_COLUMNS, PANEL_WIDTH, PANEL_GAP)
        y_positions = list(
            reversed(centered_positions(GRID_ROWS, PANEL_LENGTH, PANEL_GAP))
        )
        panel_center_z = PANEL_TOP_Z - PANEL_THICKNESS / 2.0
        number = 1

        for row, y in enumerate(y_positions, start=1):
            for column, x in enumerate(x_positions, start=1):
                created.append(
                    create_cube(
                        actor_subsystem,
                        cube_mesh,
                        f"Panel_{number:02d}_R{row}_C{column}",
                        unreal.Vector(x, y, panel_center_z),
                        unreal.Vector(
                            PANEL_WIDTH + PANEL_EDGE_OVERLAP,
                            PANEL_LENGTH + PANEL_EDGE_OVERLAP,
                            PANEL_THICKNESS,
                        ),
                        PANEL_FOLDER,
                        unreal.CollisionEnabled.NO_COLLISION,
                        cast_shadow=False,
                    )
                )
                number += 1

    spawn = actor_subsystem.spawn_actor_from_class(
        unreal.TargetPoint,
        SPAWN_LOCATION,
        unreal.Rotator(),
        False,
    )
    if spawn:
        configure_actor(spawn, "REFERENCE_GameSpawn_0_0_100", SPAWN_FOLDER)
        created.append(spawn)

    if CREATE_LIGHTING:
        directional = actor_subsystem.spawn_actor_from_class(
            unreal.DirectionalLight,
            unreal.Vector(0.0, 0.0, 500.0),
            DIRECTIONAL_LIGHT_ROTATION,
            False,
        )
        if directional:
            configure_actor(directional, f"L_{ARENA_NAME}_Directional", LIGHT_FOLDER)
            component = directional.get_component_by_class(unreal.DirectionalLightComponent)
            if component:
                component.set_editor_property("intensity", DIRECTIONAL_LIGHT_INTENSITY)
            created.append(directional)

        sky = actor_subsystem.spawn_actor_from_class(
            unreal.SkyLight,
            unreal.Vector(0.0, 0.0, 100.0),
            unreal.Rotator(),
            False,
        )
        if sky:
            configure_actor(sky, f"L_{ARENA_NAME}_Sky", LIGHT_FOLDER)
            component = sky.get_component_by_class(unreal.SkyLightComponent)
            if component:
                component.set_editor_property("intensity", SKY_LIGHT_INTENSITY)
            created.append(sky)

        atmosphere = actor_subsystem.spawn_actor_from_class(
            unreal.SkyAtmosphere,
            unreal.Vector(),
            unreal.Rotator(),
            False,
        )
        if atmosphere:
            configure_actor(atmosphere, f"SkyAtmosphere_{ARENA_NAME}", LIGHT_FOLDER)
            created.append(atmosphere)

    actor_subsystem.set_selected_level_actors(created)
    if not level_subsystem.save_current_level():
        unreal.log_warning("The arena was generated, but the level save was not confirmed.")

    unreal.EditorDialog.show_message(
        "Arena Blockout Complete",
        f"Generated {len(created)} actors for {ARENA_NAME}.",
        unreal.AppMsgType.OK,
    )


try:
    build_arena()
except Exception as error:
    unreal.log_error(f"[Configurable Arena] {error}")
    unreal.EditorDialog.show_message(
        "Arena Generation Failed",
        str(error),
        unreal.AppMsgType.OK,
    )
